### ISSUE TITLE
ServiceBusException while creating client

### ISSUE THREAD

**Issue by jtaubensee** [Azure/azure-event-hubs-java#7]
_From @Sshubb on September 15, 2016 12:28_

> Hi all,
> I am using javaeventhublibrary version 0.8.2 latest version and i have written the following code for sending data:

```
ConnectionStringBuilder connStr = new ConnectionStringBuilder("connectionstring"); 
byte[] payloadBytes = valueChangeMessage.data.get().toString().getBytes("UTF-8");
EventData sendEvent = new EventData(payloadBytes);
EventHubClient ehClient = EventHubClient.createFromConnectionStringSync(connStr.toString());
ehClient.sendSync(sendEvent);
```

> And after executing this code i am getting following error:

```
Sep 15, 2016 5:32:44 PM com.microsoft.azure.servicebus.MessagingFactory$RunReactor run
WARNING: UnHandled exception while processing events in reactor:
java.lang.NullPointerException
org.apache.qpid.proton.engine.impl.EventImpl.dispatch(EventImpl.java:112)
org.apache.qpid.proton.reactor.impl.ReactorImpl.dispatch(ReactorImpl.java:309)
org.apache.qpid.proton.reactor.impl.ReactorImpl.process(ReactorImpl.java:276)
com.microsoft.azure.servicebus.MessagingFactory$RunReactor.run(MessagingFactory.java:332)
java.lang.Thread.run(Thread.java:745)Cause: null
org.apache.qpid.proton.engine.impl.SaslImpl.plain(SaslImpl.java:446)
com.microsoft.azure.servicebus.amqp.ConnectionHandler.onConnectionBound(ConnectionHandler.java:74)
org.apache.qpid.proton.engine.BaseHandler.handle(BaseHandler.java:131)
org.apache.qpid.proton.engine.impl.EventImpl.dispatch(EventImpl.java:108)
org.apache.qpid.proton.reactor.impl.ReactorImpl.dispatch(ReactorImpl.java:309)
org.apache.qpid.proton.reactor.impl.ReactorImpl.process(ReactorImpl.java:276)
com.microsoft.azure.servicebus.MessagingFactory$RunReactor.run(MessagingFactory.java:332)
java.lang.Thread.run(Thread.java:745)
Sep 15, 2016 5:32:44 PM com.cognizant.iotworkbench.Channel.CatChannel sendPOST
SEVERE: null
com.microsoft.azure.servicebus.ServiceBusException: java.lang.NullPointerException, TrackingId: fcf793be-47b9-48a1-ac05-fb036fe6f69e, at: 2016-09-15T17:32:44.917+05:30[Asia/Calcutta]
    at com.microsoft.azure.servicebus.MessagingFactory$RunReactor.run(MessagingFactory.java:357)
    at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.NullPointerException
    at org.apache.qpid.proton.engine.impl.SaslImpl.plain(SaslImpl.java:446)
    at com.microsoft.azure.servicebus.amqp.ConnectionHandler.onConnectionBound(ConnectionHandler.java:74)
    at org.apache.qpid.proton.engine.BaseHandler.handle(BaseHandler.java:131)
    at org.apache.qpid.proton.engine.impl.EventImpl.dispatch(EventImpl.java:108)
    at org.apache.qpid.proton.reactor.impl.ReactorImpl.dispatch(ReactorImpl.java:309)
    at org.apache.qpid.proton.reactor.impl.ReactorImpl.process(ReactorImpl.java:276)
    at com.microsoft.azure.servicebus.MessagingFactory$RunReactor.run(MessagingFactory.java:332)
    ... 1 more
```

> Please let me know what can be the possible issue???

_Copied from original issue: Azure/azure-event-hubs#263_

**Comment by jtaubensee** [comment]
_From @Sshubb on September 15, 2016 13:25_

> Also I am getting this issue when i am using different connectionstring:

com.microsoft.azure.servicebus.ServiceBusException: java.lang.IllegalArgumentException, TrackingId: 9c524ed0-3faf-4ce1-b787-6266b350b63d, at: 2016-09-15T18:46:01.634+05:30[Asia/Calcutta]
	at com.microsoft.azure.servicebus.MessagingFactory$RunReactor.run(MessagingFactory.java:357)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.IllegalArgumentException
	at java.nio.Buffer.position(Buffer.java:244)
	at org.apache.qpid.proton.engine.impl.ssl.SimpleSslTransportWrapper.pop(SimpleSslTransportWrapper.java:411)
	at org.apache.qpid.proton.engine.impl.ssl.SslImpl$UnsecureClientAwareTransportWrapper.pop(SslImpl.java:185)
	at org.apache.qpid.proton.engine.impl.TransportImpl.pop(TransportImpl.java:1476)
	at org.apache.qpid.proton.reactor.impl.SelectorImpl.select(SelectorImpl.java:145)
	at org.apache.qpid.proton.reactor.impl.IOHandler.handleQuiesced(IOHandler.java:57)
	at org.apache.qpid.proton.reactor.impl.IOHandler.onUnhandled(IOHandler.java:381)
	at org.apache.qpid.proton.engine.BaseHandler.onReactorQuiesced(BaseHandler.java:87)
	at org.apache.qpid.proton.engine.BaseHandler.handle(BaseHandler.java:206)
	at org.apache.qpid.proton.engine.impl.EventImpl.dispatch(EventImpl.java:108)
	at org.apache.qpid.proton.reactor.impl.ReactorImpl.dispatch(ReactorImpl.java:309)
	at org.apache.qpid.proton.reactor.impl.ReactorImpl.process(ReactorImpl.java:277)
	at com.microsoft.azure.servicebus.MessagingFactory$RunReactor.run(MessagingFactory.java:332)
	... 1 more

**Comment by jtaubensee** [comment]
_From @SreeramGarlapati on September 15, 2016 17:15_

what is the format of connectionString being used here (& also point me which ex. lead you to use that format) ?

While we fix this, use the <a href="https://github.com/Azure/azure-event-hubs/blob/master/java/azure-eventhubs-samples/src/main/java/com/microsoft/azure/eventhubs/samples/Send.java#L23">below way</a> to create connectionString make progress:
```
final String namespaceName = "----ServiceBusNamespaceName-----";
final String eventHubName = "----EventHubName-----";
final String sasKeyName = "-----SharedAccessSignatureKeyName-----";
final String sasKey = "---SharedAccessSignatureKey----";
ConnectionStringBuilder connStr = new ConnectionStringBuilder(namespaceName, eventHubName, sasKeyName, sasKey);
```

**Comment by jtaubensee** [comment]
_From @Sshubb on September 15, 2016 18:29_

Hi sreeram,
I tried the below way as well .Even it is also creating the same connection string which i am using.

**Comment by jtaubensee** [comment]
_From @SreeramGarlapati on September 15, 2016 20:49_

can you modify the values and show the connection string format..

**Comment by jtaubensee** [comment]
_From @Sshubb on September 16, 2016 5:52_

Hi Sreeram ,
i have tried bothe the constructors of ConnectionStringBuilder class : 
    * ConnectionStringBuilder connStr = new ConnectionStringBuilder(namespaceName, eventHubName, sasKeyName, sasKey);
*ConnectionStringBuilder connStr = new ConnectionStringBuilder("connectionstring"); 

And both are giving the same exception ....

And For the connectionString Format is 
"Endpoint=sb://Namespacename.servicebus.windows.net/;SharedAccessKeyName=blsender;SharedAccessKey=key;EntityPath=eventhubname"

Can it be some access issues or proxy issues???

Can you give me a quick workaround as I have some urgent deleverables??

i used this link :https://azure.microsoft.com/en-us/documentation/articles/event-hubs-java-ephcs-getstarted/

Regards,
Shubanker

**Comment by jtaubensee** [comment]
_From @SreeramGarlapati on September 16, 2016 18:13_

This doesn't looklike a proxy issue.

I just **found this** in your stacktrace:
Sep 15, 2016 5:32:44 PM com.cognizant**.iotworkbench**.Channel.CatChannel sendPOST
SEVERE: null

Did you also have IOT client sdk's in the same POM ? Do you have any other library which can bring conflicting dependencies of <a href="http://mvnrepository.com/artifact/com.microsoft.azure/azure-eventhubs/0.8.2">eventhubs client</a> ? For ex: IOTHub actually brings in an older version of proton-j - and you can run into these kind of exceptions.

I would recommend you to isolate the problem: Start with - create a fresh java jar without anything except eventhubs send code and clean POM.xml file without any other dependencies - see if this works. If it doesn't contact us.
If it does - then add all the environment variables to this equation & findout which one is bringing the conflicting dependency.

(tagging IOT-SDK folks @dcristoloveanu / @jasmineymlo )

**Comment by jtaubensee** [comment]
_From @SreeramGarlapati on October 31, 2016 20:40_

@Sshubb - any luck finding the issue ?

**Comment by JamesBirdsall** [comment]
This looks like a known Proton-J issue https://issues.apache.org/jira/browse/PROTON-1275 which is fixed in Proton-J 0.15.0. We have released our client version 0.9.0 which among other things updates the Proton-J dependency.

**Comment by joearkay** [comment]
Hi @JamesBirdsall I have had an identical problem. Checked, and I am using the client version 0.9.0 which indicates the problem is still not fixed. Here's a recent exception for reference: 

`com.microsoft.azure.servicebus.ServiceBusException: connection aborted
	at com.microsoft.azure.servicebus.ExceptionUtil.toException(ExceptionUtil.java:93)
	at com.microsoft.azure.servicebus.MessagingFactory.onConnectionError(MessagingFactory.java:187)
	at com.microsoft.azure.servicebus.amqp.ConnectionHandler.onTransportError(ConnectionHandler.java:105)
	at org.apache.qpid.proton.engine.BaseHandler.handle(BaseHandler.java:191)
	at org.apache.qpid.proton.engine.impl.EventImpl.dispatch(EventImpl.java:108)
	at org.apache.qpid.proton.reactor.impl.ReactorImpl.dispatch(ReactorImpl.java:309)
	at org.apache.qpid.proton.reactor.impl.ReactorImpl.process(ReactorImpl.java:276)
	at com.microsoft.azure.servicebus.MessagingFactory$RunReactor.run(MessagingFactory.java:340)
	at java.lang.Thread.run(Thread.java:745)`

**Comment by SreeramGarlapati** [comment]
Hi @joearkay - exception shows that connection aborted 
- which doesn't seem abnormal (based on network conditions) - if you are seeing this error once in a while - it could be due to a variety of reasons - like a n/w glitch on client - EventHub service node to which the client is talking to reboots etc.
if you are seeing any other problem for ex: you can never connect to EventHub service due to this ? and this is one of the symptoms - please elaborate the problem...?

**Comment by hem1891** [comment]
I tried to run the java publisher by trying both the constructors. I get the same error. Anyone able to get around this?

Exception in thread "main" com.microsoft.azure.servicebus.ServiceBusException: connection aborted
        at com.microsoft.azure.servicebus.ExceptionUtil.toException(ExceptionUtil.java:93)
        at com.microsoft.azure.servicebus.MessagingFactory.onConnectionError(MessagingFactory.java:187)
        at com.microsoft.azure.servicebus.amqp.ConnectionHandler.onTransportError(ConnectionHandler.java:105)
        at org.apache.qpid.proton.engine.BaseHandler.handle(BaseHandler.java:191)
        at org.apache.qpid.proton.engine.impl.EventImpl.dispatch(EventImpl.java:108)
        at org.apache.qpid.proton.reactor.impl.ReactorImpl.dispatch(ReactorImpl.java:309)
        at org.apache.qpid.proton.reactor.impl.ReactorImpl.process(ReactorImpl.java:276)
        at com.microsoft.azure.servicebus.MessagingFactory$RunReactor.run(MessagingFactory.java:340)
        at java.lang.Thread.run(Thread.java:745)

**Comment by joearkay** [comment]
You need to close the connection after, which ISN'T documented in Microsoft's examples:

            ehClient.sendSync(sendEvent); 
            ehClient.closeSync();

**Comment by hem1891** [comment]
After i tried closing the ehClient i get illegalArgumentException here is my error. 

Dec 09, 2016 12:50:42 PM com.microsoft.azure.servicebus.MessagingFactory$RunReactor run
WARNING: UnHandled exception while processing events in reactor:
java.lang.IllegalArgumentException
org.apache.qpid.proton.engine.impl.EventImpl.dispatch(EventImpl.java:112)
org.apache.qpid.proton.reactor.impl.ReactorImpl.dispatch(ReactorImpl.java:307)
org.apache.qpid.proton.reactor.impl.ReactorImpl.process(ReactorImpl.java:276)
com.microsoft.azure.servicebus.MessagingFactory$RunReactor.run(MessagingFactory.java:327)
java.lang.Thread.run(Thread.java:745)Cause: null
java.nio.Buffer.position(Buffer.java:244)
org.apache.qpid.proton.engine.impl.ssl.SimpleSslTransportWrapper.pop(SimpleSslTransportWrapper.java:411)
org.apache.qpid.proton.engine.impl.ssl.SslImpl$UnsecureClientAwareTransportWrapper.pop(SslImpl.java:185)
org.apache.qpid.proton.engine.impl.TransportImpl.pop(TransportImpl.java:1476)
org.apache.qpid.proton.reactor.impl.SelectorImpl.select(SelectorImpl.java:145)
org.apache.qpid.proton.reactor.impl.IOHandler.handleQuiesced(IOHandler.java:57)
org.apache.qpid.proton.reactor.impl.IOHandler.onUnhandled(IOHandler.java:381)
org.apache.qpid.proton.engine.BaseHandler.onReactorQuiesced(BaseHandler.java:87)
org.apache.qpid.proton.engine.BaseHandler.handle(BaseHandler.java:206)
org.apache.qpid.proton.engine.impl.EventImpl.dispatch(EventImpl.java:108)
org.apache.qpid.proton.reactor.impl.ReactorImpl.dispatch(ReactorImpl.java:307)
org.apache.qpid.proton.reactor.impl.ReactorImpl.process(ReactorImpl.java:276)
com.microsoft.azure.servicebus.MessagingFactory$RunReactor.run(MessagingFactory.java:327)
java.lang.Thread.run(Thread.java:745)
Exception in thread "main" com.microsoft.azure.servicebus.ServiceBusException: java.lang.IllegalArgumentException, TrackingId: 226eaa8d-c5f1-4ed3-b896-229f3f684aba, at: 2016-12-09T12:50:42.893+05:30[Asia/Calcutta]
	at com.microsoft.azure.servicebus.MessagingFactory$RunReactor.run(MessagingFactory.java:351)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.IllegalArgumentException
	at java.nio.Buffer.position(Buffer.java:244)
	at org.apache.qpid.proton.engine.impl.ssl.SimpleSslTransportWrapper.pop(SimpleSslTransportWrapper.java:411)
	at org.apache.qpid.proton.engine.impl.ssl.SslImpl$UnsecureClientAwareTransportWrapper.pop(SslImpl.java:185)
	at org.apache.qpid.proton.engine.impl.TransportImpl.pop(TransportImpl.java:1476)
	at org.apache.qpid.proton.reactor.impl.SelectorImpl.select(SelectorImpl.java:145)
	at org.apache.qpid.proton.reactor.impl.IOHandler.handleQuiesced(IOHandler.java:57)
	at org.apache.qpid.proton.reactor.impl.IOHandler.onUnhandled(IOHandler.java:381)
	at org.apache.qpid.proton.engine.BaseHandler.onReactorQuiesced(BaseHandler.java:87)
	at org.apache.qpid.proton.engine.BaseHandler.handle(BaseHandler.java:206)
	at org.apache.qpid.proton.engine.impl.EventImpl.dispatch(EventImpl.java:108)
	at org.apache.qpid.proton.reactor.impl.ReactorImpl.dispatch(ReactorImpl.java:307)
	at org.apache.qpid.proton.reactor.impl.ReactorImpl.process(ReactorImpl.java:276)
	at com.microsoft.azure.servicebus.MessagingFactory$RunReactor.run(MessagingFactory.java:327)
	... 1 more

**Comment by SreeramGarlapati** [comment]
@hem1891 : you were seeing 
`Exception in thread "main" com.microsoft.azure.servicebus.ServiceBusException: connection aborted`

This indicates the connection to SERVICEBUS namespace was aborted for some reason. Is this happening every single time you are trying to create an `EHClient` ? if so, most likely there is an environment issue that you are hitting, as a result, connecting to `your_namespace.servicebus.windows.net:5671` is being aborted (this could be due to various reasons - like if you are running the client behind a firewall etc).

**Comment by SreeramGarlapati** [comment]
@hem1891 - does the client always throw this error or do you see this intermittently ?

**Comment by SreeramGarlapati** [comment]
@hem1891:
We fixed couple of issues whose callstack looks the same in our recent release - please re-open the issue if you still see the problem with version - 0.10.0 and provide us code that can repro the issue.
We would love to fix any problem you experience using our client...

**Comment by pravekai** [comment]
I am getting the following exception while deploying my mediator class in WSO2
[2018-08-17 00:12:30,392] [EI-Core]  INFO - ProxyServiceDeployer ProxyService named 'sampleproxy' has been deployed from file : D:\Training_WSO2\wso2ei-6.2.0\tmp\carbonapps\-1234\1534444950355samplecomposite_1.0.0.car\sampleproxy_1.0.0\sampleproxy-1.0.0.xml
[2018-08-17 00:12:30,427] [EI-Core] ERROR - ClassMediatorFactory Error in instantiating class : com.eventhub.send.PublishEvent
java.lang.NoClassDefFoundError: com/microsoft/azure/eventhubs/EventHubException
	at java.lang.Class.getDeclaredConstructors0(Native Method)

**Comment by pravekai** [comment]
Could you please help me how  to resolve it
